### ISSUE TITLE
Can't open the exe

### ISSUE THREAD

**Issue by jkwyp1120** [limangox/sakamsg#1]
I have tried both windows terminal and cmd, but it loads and crashes within seconds. Hope this can be solved! Thank you!

**Comment by limangox** [comment]
Instead of running the EXE file by double-clicking, open terminal or CMD in the same folder as the EXE file and type in the corresponding file name for SAKAMSG. If you do use the above methods but still have a problem, try to describe the steps you took to solve the problem.

**Comment by jkwyp1120** [comment]
> Instead of running the EXE file by double-clicking, open terminal or CMD in the same folder as the EXE file and type in the corresponding file name for SAKAMSG. If you do use the above methods but still have a problem, try to describe the steps you took to solve the problem.

Thank you for your reply, but when I put them in the folder. I type "sakamsg-win", and it would display as the image below, and when I type "start sakamsg-win", it would open and crash within seconds. I wonder if this is the right way to do, thank you! This situations happen to both terminal and cmd.
![屏幕截图 2024-06-10 024622](https://github.com/limangox/sakamsg/assets/172196098/e876ce73-2f1d-46f7-8eb4-f22ead6b3ce0)

**Comment by limangox** [comment]
You need to follow the appropriate commands to execute the program:[How to use](https://github.com/limangox/sakamsg/blob/main/README.md#how-to-use)
