### ISSUE TITLE
遇到了問題

### ISSUE THREAD

**Issue by HowToEatPassionFruit** [limangox/sakamsg#2]
![螢幕擷取畫面 2024-06-30 022542](https://github.com/limangox/sakamsg/assets/123798145/6b0df0ca-f159-4d30-a452-c1a9ec0d3688)
遇到了這個問題，不過之前一直用都沒事。

**Comment by limangox** [comment]
![image](https://github.com/limangox/sakamsg/assets/30689352/4607a37f-4161-423a-b8f5-2ffb4b1a5dfd)
The Nogizaka46 website is under construction. Please wait until it is finished before using it
